name: Linux CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libcurl4-openssl-dev libhidapi-dev libzip-dev
        pip install build
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        sudo ldconfig
        cd -
    - name: Build libconcord Python bindings
      run: |
        cd libconcord/bindings/python
        python3 -m build
        pip install dist/*.whl
        python3 -c 'import libconcord; print(libconcord)'
        cd -
#    - name: Build concordance
#      run: |
#        cd concordance
#        mkdir m4; autoreconf --install
#        ./configure
#        make
#        sudo make install
#        cd -
#        concordance --version
        - name: Build libconcord and concordance
      run: |
        sudo apt-get install -y checkinstall

        # 1. Compile libconcord but don't package it yet
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        sudo ldconfig
        cd -

        # 2. Compile concordance
        cd concordance
        mkdir m4; autoreconf --install
        ./configure
        make
        
        # 3. Create a single package tracking files from both builds
        # We manually copy libconcord's shared libraries into the folder 
        # so checkinstall catches them all together.
        sudo cp -d /usr/local/lib/libconcord.so* /usr/local/bin/concordance .
        
        sudo checkinstall --default --pkgname=concordance make install
        
        mv *.deb ../
        cd -

    - name: Upload Debian Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: concordance-deb-package
        path: ./*.deb
