name: Linux CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libcurl4-openssl-dev libhidapi-dev libzip-dev
        pip install build
    - name: Build libconcord
      run: |
        cd libconcord
        mkdir m4; autoreconf --install
        ./configure
        make
        sudo make install
        sudo ldconfig
        cd -
    - name: Build libconcord Python bindings
      run: |
        cd libconcord/bindings/python
        python3 -m build
        pip install dist/*.whl
        python3 -c 'import libconcord; print(libconcord)'
        cd -
#    - name: Build concordance
#      run: |
#        cd concordance
#        mkdir m4; autoreconf --install
#        ./configure
#        make
#        sudo make install
#        cd -
#        concordance --version
    - name: Build and Package concordance
      run: |
        # Install checkinstall tool
        sudo apt-get install -y checkinstall
        
        # Build Concordance
        cd concordance
        mkdir m4; autoreconf --install
        ./configure
        make
        
        # Run checkinstall to create the .deb package
        # --default accepts all default prompts automatically
        # --pkgname defines the name of the package
        sudo checkinstall --default --pkgname=concordance make install
        
        # Move the newly generated .deb file out to the root directory
        mv *.deb ../
        cd -

    - name: Upload Debian Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: concordance-deb-package
        path: ./*.deb
